### ISSUE TITLE
Current stable version is broken with java.lang.NoSuchFieldError: DEFAULT_USER_AGENT

### ISSUE THREAD

**Issue by Yugen42** [eldur/jwbf#66]
```
Exception in thread "XXX" java.lang.NoSuchFieldError: DEFAULT_USER_AGENT
	at org.apache.http.impl.client.HttpClientVersion.<clinit>(HttpClientVersion.java:9)
	at net.sourceforge.jwbf.core.actions.HttpActionClient$Builder.makeUserAgentString(HttpActionClient.java:400)
	at net.sourceforge.jwbf.core.actions.HttpActionClient$Builder.build(HttpActionClient.java:386)
```

Greetings. The current stable version is broken when using Java 8 with a simple spring boot bot, because the field DEFAULT_USER_AGENT doesn't exist, however the current SNAPSHOT version works. Are there any plans for creating an updated release version so people don't have to resort to using a SNAPSHOT?

**Comment by eldur** [comment]
I am not in the office for a few weeks. A release will be possible in october

**Comment by ChrisJeamme** [comment]
The problem is still present  :/
Anyone can help me? I need the API for a school project

**Comment by ThStock** [comment]
Have you tried the latest SNAPSHOT? Which version do you use?

**Comment by eldur** [comment]
Have you tried the latest SNAPSHOT? Which version do you use?

**Comment by ChrisJeamme** [comment]
I use the last RELEASE version on the maven repo, so the 3.1.1, but I will try the 4.0.0 SNAPSHOT, thank you for your reply

**Comment by eldur** [comment]
If you need a new release, tell me please.

**Comment by ChrisJeamme** [comment]
It's works with the 4.0.0 SNAPSHOT, so it would be cool to have a RELEASE version but for my use this version is enough,
Thank you very much for your help and for your Framework !

**Comment by mooreniemi** [comment]
It's almost 2020 and this remains broken and without a warning in the readme. Is this library still being maintained?
