### ISSUE TITLE
Not working in shaded jar

### ISSUE THREAD

**Issue by Arkinator** [eldur/jwbf#70]
When running the API from a shaded JAR (when the package is bundled within a JAR) the creation of a MediaWikiBot fails with the following message:

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418) ~[na:na]
	at net.sourceforge.jwbf.JWBF.jarToEntries(JWBF.java:219) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.JWBF.jarVersionDetails(JWBF.java:148) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.JWBF.init(JWBF.java:97) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.JWBF.lazyVersion(JWBF.java:86) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.JWBF.getVersion(JWBF.java:238) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.core.actions.HttpActionClient$Builder.getJwbfVersion(HttpActionClient.java:393) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.core.actions.HttpActionClient$Builder.build(HttpActionClient.java:381) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.core.actions.HttpActionClient.of(HttpActionClient.java:468) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]
	at net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot.<init>(MediaWikiBot.java:114) ~[jwbf-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT-2b5eb]

Tested on MacOS and Raspberry PI Linux. Please use a correct classloader in this instance.

**Comment by benjaminkomen** [comment]
I had the same problem and had to fork this repo to fix it :/

**Comment by Arkinator** [comment]
yeah, unfortunately this project seems quite dead... can you send me a link?

**Comment by eldur** [comment]
@Arkinator I've changed the exception handling. Do you want to test?

Otherwise a pull request may help
